name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: noma4i
        password: ${{ secrets.DOCKERHUB_PUSH }}
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      run: |
        docker build --platform linux/amd64 -t noma4i/rotating-proxy-ng-plus:latest -t ghcr.io/noma4i/rotating-proxy-ng-plus:latest .
        docker push noma4i/rotating-proxy-ng-plus:latest
        docker push ghcr.io/noma4i/rotating-proxy-ng-plus:latest
